/**
 * Hook generujący raport PDF artykułu przez window.open + window.print().
 * Buduje samodzielny dokument HTML z inline CSS — nie klonuje DOM z Tailwindem.
 */

import { useCallback } from 'react';
import type { Lang } from '../../lib/types';

export interface ArticlePrintData {
  title: string;
  source: string;
  published?: string;
  sentimentLabel: string;
  fakeProbability?: number;
  content: string;
  link?: string;
  language: Lang;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildPrintHTML(data: ArticlePrintData, docTitle: string): string {
  const { title, source, published, sentimentLabel, fakeProbability, content, link, language } = data;

  const T = (pl: string, no: string, en: string) =>
    language === 'pl' ? pl : language === 'no' ? no : en;

  const dateStr = new Date().toLocaleDateString(
    language === 'pl' ? 'pl-PL' : language === 'no' ? 'nb-NO' : 'en-US',
    { year: 'numeric', month: 'long', day: 'numeric' }
  );

  const fakeStr =
    typeof fakeProbability === 'number'
      ? fakeProbability.toFixed(2) + '%'
      : T('Brak danych', 'Ingen data', 'No data');

  const contentParagraphs = content
    .split('\n')
    .filter(p => p.trim())
    .map(p => `<p style="margin-bottom:16px;">${escapeHtml(p)}</p>`)
    .join('');

  const linkSection = link
    ? `<div style="margin-top:35px;">
        <div style="font-size:18px;font-weight:bold;color:#0066cc;margin-bottom:15px;padding-bottom:8px;border-bottom:2px solid #e9ecef;">
          🔗 ${T('Link do oryginalnego artykułu', 'Originallenke', 'Original Article Link')}
        </div>
        <a href="${escapeHtml(link)}" style="color:#0066cc;word-break:break-all;font-size:14px;">${escapeHtml(link)}</a>
      </div>`
    : '';

  return `<!DOCTYPE html>
<html lang="${language}">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>${escapeHtml(docTitle)}</title>
  <style>
    @page {
      margin: 15mm;
      size: A4;
    }
    body {
      margin: 0;
      padding: 20px;
      font-family: Arial, Helvetica, sans-serif;
      color: #333;
      background: white;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    * {
      -webkit-print-color-adjust: exact !important;
      color-adjust: exact !important;
    }
    @media print {
      body { padding: 0; }
    }
  </style>
</head>
<body>
  <div style="max-width:800px;margin:0 auto;">

    <div style="border-bottom:3px solid #0066cc;padding-bottom:25px;margin-bottom:30px;">
      <div style="font-size:28px;font-weight:bold;color:#0066cc;margin-bottom:10px;text-align:center;">
        TruthScan AI
      </div>
      <div style="font-size:22px;font-weight:bold;color:#333;line-height:1.4;text-align:center;">
        ${escapeHtml(title)}
      </div>
    </div>

    <div style="display:grid;grid-template-columns:1fr 1fr;gap:15px;margin:25px 0;padding:20px;background:#f8f9fa;border-radius:8px;border-left:4px solid #0066cc;">
      <div style="font-size:14px;color:#555;">
        <span style="font-weight:bold;color:#333;display:inline-block;min-width:100px;">📅 ${T('Data', 'Dato', 'Date')}:</span>
        ${escapeHtml(published || T('Brak daty', 'Ingen dato', 'No date'))}
      </div>
      <div style="font-size:14px;color:#555;">
        <span style="font-weight:bold;color:#333;display:inline-block;min-width:100px;">📰 ${T('Źródło', 'Kilde', 'Source')}:</span>
        ${escapeHtml(source || '-')}
      </div>
      <div style="font-size:14px;color:#555;">
        <span style="font-weight:bold;color:#333;display:inline-block;min-width:100px;">💬 ${T('Sentyment', 'Sentiment', 'Sentiment')}:</span>
        ${escapeHtml(sentimentLabel)}
      </div>
      <div style="font-size:14px;color:#555;">
        <span style="font-weight:bold;color:#333;display:inline-block;min-width:100px;">❓ Fake News:</span>
        ${escapeHtml(fakeStr)}
      </div>
    </div>

    <div style="margin-top:35px;">
      <div style="font-size:18px;font-weight:bold;color:#0066cc;margin-bottom:15px;padding-bottom:8px;border-bottom:2px solid #e9ecef;">
        📝 ${T('TREŚĆ ARTYKUŁU', 'ARTIKKELINNHOLD', 'ARTICLE CONTENT')}
      </div>
      <div style="font-size:15px;line-height:1.7;text-align:justify;color:#333;">
        ${contentParagraphs || `<p>${T('Brak dostępnej treści artykułu.', 'Ingen artikkeltekst tilgjengelig.', 'No article content available.')}</p>`}
      </div>
    </div>

    ${linkSection}

    <div style="margin-top:60px;font-size:12px;color:#666;text-align:center;padding-top:20px;border-top:1px solid #ddd;">
      ${T('Wygenerowano przez TruthScan Analysis', 'Generert av TruthScan Analysis', 'Generated by TruthScan Analysis')} • ${dateStr}
    </div>

  </div>
</body>
</html>`;
}

export const usePDFExport = () => {
  const printArticle = useCallback((data: ArticlePrintData, docTitle: string): void => {
    const html = buildPrintHTML(data, docTitle);
    const printWindow = window.open('', '_blank');

    if (!printWindow) {
      // Fallback gdy popup zablokowany — plik HTML z pełnymi stylami inline
      const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = `${docTitle.replace(/[^a-zA-Z0-9ąćęłńóśźżĄĆĘŁŃÓŚŹŻ]/gi, '_')}.html`;
      anchor.click();
      URL.revokeObjectURL(url);
      return;
    }

    printWindow.document.write(html);
    printWindow.document.close();

    setTimeout(() => {
      printWindow.focus();
      printWindow.print();
    }, 500);
  }, []);

  return printArticle;
};
