/**
 * Komponent odpowiedzialny za renderowanie artykułu w formacie przeznaczonym do druku.
 *
 * Odpowiada za:
 * - prezentację treści artykułu w układzie zgodnym z wydrukiem / PDF,
 * - ujednolicony layout raportu (nagłówek, metadane, treść, stopka),
 * - obsługę wersji językowych (PL / EN),
 * - współpracę z mechanizmami typu react-to-print lub eksport PDF.
 */

"use client";

import React from 'react';
import locales from '../lib/locales';
import type { Lang } from '../lib/types';

interface PrintableArticleProps {
  article: {
    title: string;
    source: string;
    published?: string;
    summary?: string;
    description?: string;
    fake_probability?: number;
  };
  sentimentLabel: string;
  language: Lang;
  onClose?: () => void;
}

export const PrintableArticle: React.FC<PrintableArticleProps> = ({
  article,
  sentimentLabel,
  language,
  onClose
}) => {
  const t = locales[language] ?? locales.pl;
  const T = (pl: string, no: string, en: string) =>
    language === "pl" ? pl : language === "no" ? no : en;

  const articleContent = article.summary || article.description ||
    T("Brak dostępnej treści artykułu.", "Ingen artikkeltekst tilgjengelig.", "No article content available.");

  return (
    <div className="print-container">
      {/* Ten komponent będzie używany przez react-to-print */}
      <div className="container">
        <div className="header">
          <div className="logo">ThruScan AI</div>
          <div className="title">{article.title}</div>
        </div>
        
        <div className="metadata">
          <div className="meta-item">
            <span className="meta-label">📅 {T("Data", "Dato", "Date")}:</span>
            {article.published || t.noDate}
          </div>
          <div className="meta-item">
            <span className="meta-label">📰 {T("Źródło", "Kilde", "Source")}:</span>
            {article.source || "-"}
          </div>
          <div className="meta-item">
            <span className="meta-label">💬 {T("Sentyment", "Sentimentanalyse", "Sentiment")}:</span>
            {sentimentLabel}
          </div>
          <div className="meta-item">
            <span className="meta-label">❓ Fake News:</span>
            {typeof article.fake_probability === "number" ? article.fake_probability.toFixed(2) + "%" : T("Brak danych", "Ingen data", "No data")}
          </div>
        </div>
        
        <div className="content-section">
          <div className="content-title">
            📝 {T("TREŚĆ ARTYKUŁU", "ARTIKKELINNHOLD", "ARTICLE CONTENT")}
          </div>
          <div className="article-content">
            {articleContent.split('\n').map((paragraph, index) => 
              paragraph.trim() ? <p key={index}>{paragraph}</p> : null
            )}
          </div>
        </div>
        
        <div className="footer">
          {T("Wygenerowano przez ThruScan AI", "Generert av ThruScan AI", "Generated by ThruScan AI")} • {new Date().toLocaleDateString(language === "pl" ? "pl-PL" : language === "no" ? "no-NO" : "en-US")}
        </div>
      </div>

      <style jsx>{`
        .print-container {
          padding: 20px;
          font-family: 'Arial', 'Helvetica', sans-serif;
          color: #333;
          background: white;
        }

        .container {
          max-width: 800px;
          margin: 0 auto;
        }

        .header {
          border-bottom: 3px solid #0066cc;
          padding-bottom: 25px;
          margin-bottom: 30px;
        }

        .logo {
          font-size: 28px;
          font-weight: bold;
          color: #0066cc;
          margin-bottom: 10px;
          text-align: center;
        }

        .title {
          font-size: 22px;
          font-weight: bold;
          color: #333;
          margin-bottom: 20px;
          line-height: 1.4;
          text-align: center;
        }

        .metadata {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 15px;
          margin: 25px 0;
          padding: 20px;
          background: #f8f9fa;
          border-radius: 8px;
          border-left: 4px solid #0066cc;
        }

        .meta-item {
          font-size: 14px;
          color: #555;
        }

        .meta-label {
          font-weight: bold;
          color: #333;
          display: inline-block;
          width: 120px;
        }

        .content-section {
          margin-top: 35px;
        }

        .content-title {
          font-size: 18px;
          font-weight: bold;
          color: #0066cc;
          margin-bottom: 15px;
          padding-bottom: 8px;
          border-bottom: 2px solid #e9ecef;
        }

        .article-content {
          font-size: 15px;
          line-height: 1.7;
          text-align: justify;
        }

        .article-content p {
          margin-bottom: 16px;
        }

        .footer {
          margin-top: 60px;
          font-size: 12px;
          color: #666;
          text-align: center;
          padding-top: 20px;
          border-top: 1px solid #ddd;
        }

        @media print {
          .print-container {
            margin: 15mm;
          }
          .container {
            max-width: none;
          }
          .metadata {
            background: none;
            border: 1px solid #ddd;
            border-left: 4px solid #0066cc;
          }
        }

        @media (max-width: 768px) {
          .print-container {
            margin: 20px;
          }
          .metadata {
            grid-template-columns: 1fr;
          }
        }
      `}</style>
    </div>
  );
};